[package]
name = "fdcanusb"
version = "0.1.0"
edition = "2021"
description = "Protocol implementation for the FDCANUSB by MJBOTS"
license = "MIT"
readme = "README.md"
repository = "https://github.com/omelia-iliffe/fdcanusb-rs"

[dependencies]
hex = "0.4.3"
serial2 = "0.2.19"
log = "0.4.21"
